[project]
name = "rag-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "brandon", email = "rparks1@babson.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "llama-index-core>=0.14.25",
    "llama-index-embeddings-huggingface>=0.8.0",
    "llama-index-llms-google-genai>=0.11.2",
    "llama-index-readers-file>=0.7.0",
    "python-dotenv>=1.2.4",
    "streamlit>=1.65.0",
]

[project.scripts]
rag-chatbot = "rag_chatbot:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
